# Generated by Django 6.0.4 on 2026-04-23 00:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the field or crop block', max_length=100)),
                ('crop_type', models.CharField(help_text='Type of crop (e.g., Maize, Wheat, Rice)', max_length=100)),
                ('planting_date', models.DateField(blank=True, help_text='Date when crop was planted', null=True)),
                ('current_stage', models.CharField(choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], default='planted', help_text='Current growth stage of the crop', max_length=20)),
                ('field_size', models.DecimalField(blank=True, decimal_places=2, help_text='Field size in acres/hectares', max_digits=10, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_fields', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fields', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, help_text='Upload field image (JPG, PNG, GIF, WEBP)', null=True, upload_to='field_images/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png', 'gif', 'webp'])])),
                ('image_url', models.URLField(blank=True, help_text='Or provide external image URL', null=True)),
                ('document', models.FileField(blank=True, help_text='Upload document (PDF, CSV, Excel, Word)', null=True, upload_to='field_documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'csv', 'xlsx', 'doc', 'docx'])])),
                ('caption', models.CharField(blank=True, help_text='Description of the image/document', max_length=255, null=True)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('document', 'Document'), ('map', 'Map/Sketch'), ('report', 'Report')], default='image', help_text='Type of file', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='fields.field')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('stage_at_observation', models.CharField(blank=True, choices=[('planted', 'Planted'), ('growing', 'Growing'), ('ready', 'Ready'), ('harvested', 'Harvested')], max_length=20, null=True)),
                ('crop_health', models.CharField(blank=True, choices=[('excellent', 'Excellent'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, null=True)),
                ('pest_disease_issues', models.TextField(blank=True, null=True)),
                ('weather_conditions', models.CharField(blank=True, max_length=100, null=True)),
                ('photos', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='fields.field')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
