# Generated by Django 6.0.4 on 2026-04-23 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observation',
            name='photos',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
